/* Code generated by go generate; DO NOT EDIT. */

#include "spank_shim.h"
#include <stdbool.h>
#include <stddef.h>

static int spank_option_enabled(int val, const char *optarg, int remote);
static int spank_option_inspector_so(int val, const char *optarg, int remote);
static int spank_option_out_dir(int val, const char *optarg, int remote);


/// SPANK plugin option table.
struct spank_option spank_opts[] = {
    {
        .name    = "snccliprecon-enabled",
        .arginfo = "(1 | True) | (0 | False)",
        .usage   = "[nccl_inspector_preconf] whether to enable nccl_inspector_preconf plugin. Possible values are case-insensitive. SNCCLIPRECON_ENABLED env var is also supported.",
        .has_arg = true,
        .val     = 0,
        .cb      = spank_option_enabled,
    },
    {
        .name    = "snccliprecon-inspector-so",
        .arginfo = "PATH",
        .usage   = "[nccl_inspector_preconf] path to the NCCL Inspector SO file. SNCCLIPRECON_INSPECTOR_SO env var is also supported.",
        .has_arg = true,
        .val     = 0,
        .cb      = spank_option_inspector_so,
    },
    {
        .name    = "snccliprecon-out-dir",
        .arginfo = "PATH",
        .usage   = "[nccl_inspector_preconf] path to the directory for storing NCCL Inspector outputs. SNCCLIPRECON_OUT_DIR env var is also supported.",
        .has_arg = true,
        .val     = 0,
        .cb      = spank_option_out_dir,
    },
    SPANK_OPTIONS_TABLE_END
};

/**
 * Register plugin arguments as SPANK options.
 *
 * @param spank SPANK context.
 *
 * @retval ESPANK_SUCCESS Successfully registered options.
 * @retval ESPANK_ERROR Something went wrong.
 */
spank_err_t snccliprecon_args_register(spank_t spank) {
    spank_err_t res = ESPANK_SUCCESS;

    for (int i = 0; spank_opts[i].name != NULL; ++i) {
        res = spank_option_register(spank, &spank_opts[i]);
        if (res != ESPANK_SUCCESS) {
            snccliprecon_log_error_fmt(
                "Cannot register option %s: %s",
                spank_opts[i].name,
                spank_strerror(res)
            );
            return ESPANK_ERROR;
        }
    }

    return res;
}


/**
 * Implementation of enabled option registration callback.
 *
 * @related spank_opt_cb_f
 */
static int spank_option_enabled(int val, const char *optarg, int remote) {
    (void)val;
    (void)remote;

    if (optarg == NULL || *optarg == '\0') {
        snccliprecon_log_error_fmt(
            "--%s: argument required",
            "snccliprecon-enabled"
        );
        return ESPANK_BAD_ARG;
    }

    return snccliprecon_parse_option(
        "enabled",
        optarg
    );
}

/**
 * Implementation of inspector-so option registration callback.
 *
 * @related spank_opt_cb_f
 */
static int spank_option_inspector_so(int val, const char *optarg, int remote) {
    (void)val;
    (void)remote;

    if (optarg == NULL || *optarg == '\0') {
        snccliprecon_log_error_fmt(
            "--%s: argument required",
            "snccliprecon-inspector-so"
        );
        return ESPANK_BAD_ARG;
    }

    return snccliprecon_parse_option(
        "inspector-so",
        optarg
    );
}

/**
 * Implementation of out-dir option registration callback.
 *
 * @related spank_opt_cb_f
 */
static int spank_option_out_dir(int val, const char *optarg, int remote) {
    (void)val;
    (void)remote;

    if (optarg == NULL || *optarg == '\0') {
        snccliprecon_log_error_fmt(
            "--%s: argument required",
            "snccliprecon-out-dir"
        );
        return ESPANK_BAD_ARG;
    }

    return snccliprecon_parse_option(
        "out-dir",
        optarg
    );
}

