package optionrender

import (
	"bytes"
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/nebius/nccl-inspector-preconf/internal/arg"
	"github.com/nebius/nccl-inspector-preconf/internal/plugin"
)

type templateArg struct {
	Name         string
	DisplayName  string
	Usage        string
	ValueInfo    string
	HasArg       string
	Callback     string
	CNameLiteral string
}

type templateData struct {
	Prefix string
	Args   []templateArg
}

var renderTemplate = template.Must(template.New("spank-options").Funcs(template.FuncMap{
	"cString": cString,
}).Parse(
	// language=cgo
	`/* Code generated by go generate; DO NOT EDIT. */

#include "spank_shim.h"
#include <stdbool.h>
#include <stddef.h>

{{ range .Args -}}
static int {{ .Callback }}(int val, const char *optarg, int remote);
{{ end }}

/// SPANK plugin option table.
struct spank_option spank_opts[] = {
{{- range .Args }}
    {
        .name    = {{ cString .Name }},
        .arginfo = {{ cString .ValueInfo }},
        .usage   = {{ cString .Usage }},
        .has_arg = {{ .HasArg }},
        .val     = 0,
        .cb      = {{ .Callback }},
    },
{{- end }}
    SPANK_OPTIONS_TABLE_END
};

/**
 * Register plugin arguments as SPANK options.
 *
 * @param spank SPANK context.
 *
 * @retval ESPANK_SUCCESS Successfully registered options.
 * @retval ESPANK_ERROR Something went wrong.
 */
spank_err_t {{ .Prefix }}_args_register(spank_t spank) {
    spank_err_t res = ESPANK_SUCCESS;

    for (int i = 0; spank_opts[i].name != NULL; ++i) {
        res = spank_option_register(spank, &spank_opts[i]);
        if (res != ESPANK_SUCCESS) {
            {{ .Prefix }}_log_error_fmt(
                "Cannot register option %s: %s",
                spank_opts[i].name,
                spank_strerror(res)
            );
            return ESPANK_ERROR;
        }
    }

    return res;
}

{{ range .Args }}
/**
 * Implementation of {{ .DisplayName }} option registration callback.
 *
 * @related spank_opt_cb_f
 */
static int {{ .Callback }}(int val, const char *optarg, int remote) {
    (void)val;
    (void)remote;

    if (optarg == NULL || *optarg == '\0') {
        {{ $.Prefix }}_log_error_fmt(
            "--%s: argument required",
            {{ cString .Name }}
        );
        return ESPANK_BAD_ARG;
    }

    return {{ $.Prefix }}_parse_option(
        {{ .CNameLiteral }},
        optarg
    );
}
{{ end }}
`))

// Render writes the generated SPANK options C source to w.
func Render(w io.Writer) error {
	return renderTemplate.Execute(w, templateData{
		Prefix: plugin.Prefix,
		Args:   makeTemplateArgs(arg.Args),
	})
}

// RenderString returns the generated SPANK options C source as a string.
func RenderString() (string, error) {
	var buffer bytes.Buffer
	if err := Render(&buffer); err != nil {
		return "", err
	}

	return buffer.String(), nil
}

// makeTemplateArgs converts Go argument definitions into template input.
func makeTemplateArgs(args []arg.Arg) []templateArg {
	rendered := make([]templateArg, 0, len(args))
	for _, current := range args {
		optionName := fmt.Sprintf("%s-%s", plugin.Prefix, current.Name)
		rendered = append(rendered, templateArg{
			Name:         optionName,
			DisplayName:  current.Name,
			Usage:        current.Usage,
			ValueInfo:    current.ValueInfo,
			HasArg:       renderBool(current.HasValue),
			Callback:     renderCallbackName(current.Name),
			CNameLiteral: cString(current.Name),
		})
	}

	return rendered
}

// renderBool renders a C boolean literal.
func renderBool(value bool) string {
	if value {
		return "true"
	}

	return "false"
}

// renderCallbackName renders the C callback symbol for one argument.
func renderCallbackName(name string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_")
	return fmt.Sprintf("spank_option_%s", replacer.Replace(name))
}

// cString renders a Go string as a C string literal.
func cString(value string) string {
	var builder strings.Builder
	builder.Grow(len(value) + 2)
	builder.WriteByte('"')

	for _, char := range value {
		switch char {
		case '\\':
			builder.WriteString(`\\`)
		case '"':
			builder.WriteString(`\"`)
		case '\n':
			builder.WriteString(`\n`)
		case '\t':
			builder.WriteString(`\t`)
		default:
			builder.WriteRune(char)
		}
	}

	builder.WriteByte('"')
	return builder.String()
}
